version: '3.7'

services: 
  web: 
    build: ./app
    command: flask run 0.0.0.0:5000
    volumes: 
      - ./app/:/usr/src/app/
    ports: 
      - 5000:5000
    env_file: 
      - ./.env.dev
    depends_on: 
      - db

  db: 
    image: postgres:12.5-alpine 
    volumes: 
      - postgres_data:/var/lib/postgresql/data/
    environment: 
      - POSTGRES_USER=project
      - POSTGRES_PASSWORD=project
      - POSTGRES_DB=project_dev
  
volumes: 
  postgres_data:
